name: Feature request
description: Suggest a feature idea for Project.
labels:
  - 'Feature Request'
  - 'type: feature'
body:
  - type: markdown
    attributes:
      value: |
        > Thanks for taking the time to fill out this feature request correctly.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen. Ex. The Project would rock even more if [...]
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Not obligatory, but suggest an idea for implementing addition or change
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
