---
name: "📚 Feedback form"
about: Describe a problem, suggest a new idea or functionality for the project
title: ''
labels: 'type: feature'
assignees: ''
---

name: Project documentation
description: An issue about the Project documentation
labels:
  - 'Documentation'
body:

  - type: markdown
    attributes:
      value: |
        > Report only an issue related to the Project documentation

  - type: textarea
    id: what
    attributes:
      label: What is the issue about the documentation?
    validations:
      required: true
