blank_issues_enabled: false

contact_links:
  - name: Question
    url: https://github.com/see7e/github-templates/discussions/new?category=q-a
    about: >
      Questions should go to available Q&A (or other related) Category of the Discussions tab.
      GitHub issues are for bug reports and suggestions for new features.